INSERT INTO DEVICE (ID, SYSTEM_NAME, SYSTEM_NAME_CONCAT, DEVICE_TYPE)
VALUES(1, 'Windows 10 Ultimate', 'Windows10Ultimate', 0);
INSERT INTO DEVICE (ID, SYSTEM_NAME, SYSTEM_NAME_CONCAT, DEVICE_TYPE)
VALUES(2, 'MacBook Pro', 'MacBookPro', 1);

INSERT INTO SERVICE (ID, NAME, NAME_CONCAT, COST) VALUES(1, 'Cost Per Device', 'CostPerDevice', 4.00);
INSERT INTO SERVICE (ID, NAME, NAME_CONCAT, COST) VALUES(2, 'Windows Antivirus', 'WindowsAntivirus', 5.00);
INSERT INTO SERVICE (ID, NAME, NAME_CONCAT, COST) VALUES(3, 'Mac Antivirus', 'MacAntivirus', 7.00);
INSERT INTO SERVICE (ID, NAME, NAME_CONCAT, COST) VALUES(4, 'Backup', 'Backup', 3.00);
INSERT INTO SERVICE (ID, NAME, NAME_CONCAT, COST) VALUES(5, 'PSA', 'PSA', 2.00);
INSERT INTO SERVICE (ID, NAME, NAME_CONCAT, COST) VALUES(6, 'Screen Share', 'ScreenShare', 1.00);

INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (1, 1);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (1, 2);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (1, 4);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (1, 6);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (2, 1);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (2, 3);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (2, 4);
INSERT INTO SERVICE_DEVICE (DEVICE_ID, SERVICE_ID) VALUES (2, 6);

INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES (1,'dev', '$2a$10$b0oXDkBlVzKwhMaEtdGlgeYARHVrfImTyuEy9vceh0vDCO1l/wwKG');
